# name: CD
# on:
#   push:
#     branches: [ master ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     env:
#       SSHPASS: ${{ secrets.APP_PASS }}

#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Build Vue.js frontend
#         run: |
#           cd Front-CarbonTrack
#           npm install
#           npm run build
#           cd ..

#       - name: APT UPDATE and INSTALL SSHPASS
#         run: |
#           sudo apt update && sudo apt install -y sshpass

#       - name: Deploy
#         run: |
#           sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} "
#             cd CarbonTrack && git pull origin master &&
#             cd Back-CarbonTrack && npm install && npx prisma migrate deploy &&
#             npm install -g pm2 &&
#             pm2 start npm --name back-carbontrack -- run start || pm2 restart back-carbontrack &&
#             cd ../Front-CarbonTrack && npm install && npm run build"