name: carbontrack

services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CarbonTrack
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d CarbonTrack']
      interval: 5s
      timeout: 5s
      retries: 12

  adminer:
    image: adminer:6
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '8081:8080'
    depends_on:
      db:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:v1
    restart: unless-stopped
    ports:
      - '8026:8025'

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    restart: unless-stopped

    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx nodemon --watch src --ignore src/generated -e js,ts,json src/server.js"
    env_file:
      - apps/api/.env
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://postgres:root@db:5432/CarbonTrack
      FRONTEND_URL: http://localhost:5173

      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      SMTP_USER: ''
      SMTP_PASS: ''
    ports:
      - '3000:3000'

    volumes:
      - ./apps/api/prisma:/app/apps/api/prisma
    develop:
      watch:
        - action: sync
          path: ./apps/api/src
          target: /app/apps/api/src
          ignore:
            - generated/
        - action: sync
          path: ./apps/api/test
          target: /app/apps/api/test
        - action: sync+restart
          path: ./apps/api/prisma.config.js
          target: /app/apps/api/prisma.config.js
        - action: rebuild
          path: ./apps/api/package.json
        - action: rebuild
          path: ./package-lock.json
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: dev
    restart: unless-stopped
    env_file:
      - apps/web/.env
    ports:
      - '5173:5173'
    develop:
      watch:
        - action: sync
          path: ./apps/web/src
          target: /app/apps/web/src
        - action: sync
          path: ./apps/web/test
          target: /app/apps/web/test
        - action: sync
          path: ./apps/web/public
          target: /app/apps/web/public
        - action: sync
          path: ./apps/web/index.html
          target: /app/apps/web/index.html
        - action: sync+restart
          path: ./apps/web/vite.config.js
          target: /app/apps/web/vite.config.js
        - action: rebuild
          path: ./apps/web/package.json
        - action: rebuild
          path: ./package-lock.json
    depends_on:
      - api

volumes:
  db-data:
